# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\",\n\x0bPingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\".\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x61live\x18\x02 \x01(\x08\x32\x35\n\x04Raft\x12-\n\x04Ping\x12\x11.raft.PingRequest\x1a\x12.raft.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=20
  _globals['_PINGREQUEST']._serialized_end=64
  _globals['_PINGRESPONSE']._serialized_start=66
  _globals['_PINGRESPONSE']._serialized_end=112
  _globals['_RAFT']._serialized_start=114
  _globals['_RAFT']._serialized_end=167
# @@protoc_insertion_point(module_scope)
